### ISSUE TITLE
🐞Weird Crash happening 

### ISSUE THREAD

**Issue by WelpSTudent** [LeoBeliik/ExtremeSoundMuffler#33]
### Extreme sound muffler version

3.19

### Forge version

39.0.9

### Describe the bug

Crash on launch

### Steps to reproduce

Im not sure what is causing this crash

### Crashlog

https://pastebin.com/5BsVhEc4

**Comment by LeoBeliik** [comment]
Could you send your latest.log or debug.log

**Comment by WelpSTudent** [comment]
[latest.log](https://github.com/LeoBeliik/ExtremeSoundMuffler/files/7831015/latest.log)

**Comment by LeoBeliik** [comment]
Hmm, I have no clue why this happens, the configs seems to have failed to load, try deleting the config/extremesoundmuffler-client.toml file and see if it crashes again

**Comment by LeoBeliik** [comment]
I looked again at this issue and I don't know how I missed this the first time.
`net.minecraftforge.fml.ModLoadingException: Mod §ebackpacked§r requires §6forge§r §o39.0.10 or above§r
§7Currently, §6forge§r§7 is §o39.0.9`
that mod needs a newer forge version, that's why is crashing.
I'm closing this, if the problem persist I'll reopen it
